name: Test macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test-macos-arm64:
    runs-on: macos-latest
    permissions:
      checks: write
      pull-requests: write
      contents: read
      packages: read

    steps:
      - name: Cleanup workspace
        run: |
          sudo rm -rf ${{ github.workspace }}/*

      - uses: actions/checkout@v4

      - name: Run uname -a
        run: |
          uname -a

      - name: Install Erlang and Elixir
        run: |
          brew install erlang elixir

      - name: Install build tools
        run: |
          brew install autoconf automake libtool

      - name: Install OpenSSL
        run: |
          brew install openssl@3

      - name: Checkout SoftHSMv2 at tag 2.6.1 (shallow clone)
        run: |
          git clone --branch 2.6.1 --depth 1 https://github.com/softhsm/SoftHSMv2.git

      - name: Configure SoftHSM Build
        run: |
          mkdir ${{ github.workspace }}/softhsm
          cd SoftHSMv2
          ./autogen.sh
          ./configure --prefix=${{ github.workspace }}/softhsm --enable-ecc --enable-eddsa --with-openssl=/opt/homebrew/opt/openssl@3 --disable-gost

      - name: Build SoftHSM
        run: |
          make

      - name: Install SoftHSM
        run: |
          make install

      - name: Install hex and get dependencies
        run: |
          mix local.hex --force && mix deps.get && mix compile --warnings-as-errors && mix test --cover || true