name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        include:
          # Ubuntu x86_64
          - os: ubuntu-24.04
            arch: amd64
          # Ubuntu ARM64 (via QEMU)
          - os: ubuntu-24.04
            arch: arm64
          # macOS ARM64 (M1/M2)
          - os: macos-latest
            arch: arm64

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        if: matrix.os == 'ubuntu-24.04' && matrix.arch == 'arm64'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Install Elixir and dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-24.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y elixir erlang-dev build-essential softhsm2

      - name: Install Elixir and dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install elixir erlang softhsm

      - name: Install Hex package manager
        run: mix local.hex --force

      - name: Download PKCS#11 headers
        run: |
          cd c_src
          curl -O https://raw.githubusercontent.com/oasis-tcs/pkcs11/master/published/3-01/pkcs11.h
          curl -O https://raw.githubusercontent.com/oasis-tcs/pkcs11/master/published/3-01/pkcs11t.h
          curl -O https://raw.githubusercontent.com/oasis-tcs/pkcs11/master/published/3-01/pkcs11f.h

      - name: Initialize SoftHSM tokens (Ubuntu)
        if: matrix.os == 'ubuntu-24.04'
        run: |
          sudo mkdir -p /var/lib/softhsm/tokens/
          sudo softhsm2-util --init-token --slot 0 --label "Test Token" --pin 1234 --so-pin 12345678

      - name: Initialize SoftHSM tokens (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          mkdir -p ~/Library/softhsm/tokens/
          softhsm2-util --init-token --slot 0 --label "Test Token" --pin 1234 --so-pin 12345678

      - name: Get dependencies
        run: mix deps.get

      - name: Run tests
        run: mix test
        env:
          MIX_ENV: test

      - name: Compile
        run: mix compile
        env:
          MIX_ENV: test
