name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        include:
          # Ubuntu x86_64
          - os: ubuntu-22.04
            arch: amd64
          # macOS ARM64 (M1/M2)
          - os: macos-latest
            arch: arm64

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        if: matrix.os == 'ubuntu-22.04' && matrix.arch == 'arm64'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Install Elixir and dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-22.04'
        run: |
          # Install build dependencies
          sudo apt-get update
          sudo apt-get install -y build-essential autoconf m4 libncurses5-dev libwxgtk3.0-gtk3-dev libgl1-mesa-dev libglu1-mesa-dev libpng-dev libssh-dev unixodbc-dev xsltproc fop libxml2-utils libncurses-dev openjdk-11-jdk softhsm2
          
          # Install asdf
          git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.13.1
          echo '. "$HOME/.asdf/asdf.sh"' >> ~/.bashrc
          echo '. "$HOME/.asdf/completions/asdf.bash"' >> ~/.bashrc
          source ~/.asdf/asdf.sh
          
          # Install Erlang and Elixir plugins
          asdf plugin add erlang
          asdf plugin add elixir
          
          # Install specific versions (adjust versions as needed)
          asdf install erlang 26.2.1
          asdf install elixir 1.15.7-otp-26
          
          # Set as global versions
          asdf global erlang 26.2.1
          asdf global elixir 1.15.7-otp-26

      - name: Install Elixir and dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          # Install dependencies via Homebrew
          brew install erlang elixir wxwidgets openssl@1.1 autoconf softhsm

      - name: Install Hex package manager
        run: mix local.hex --force

      - name: Download PKCS#11 headers
        run: |
          cd c_src
          curl -O https://raw.githubusercontent.com/oasis-tcs/pkcs11/master/published/3-01/pkcs11.h
          curl -O https://raw.githubusercontent.com/oasis-tcs/pkcs11/master/published/3-01/pkcs11t.h
          curl -O https://raw.githubusercontent.com/oasis-tcs/pkcs11/master/published/3-01/pkcs11f.h

      - name: Initialize SoftHSM tokens (Ubuntu)
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo mkdir -p /var/lib/softhsm/tokens/
          sudo softhsm2-util --init-token --slot 0 --label "Test Token" --pin 1234 --so-pin 12345678

      - name: Initialize SoftHSM tokens (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          mkdir -p ~/Library/softhsm/tokens/
          softhsm2-util --init-token --slot 0 --label "Test Token" --pin 1234 --so-pin 12345678

      - name: Get dependencies
        run: mix deps.get

      - name: Run tests
        run: mix test --cover
        env:
          MIX_ENV: test
        continue-on-error: true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            _build/test/lib/*/test-*.xml
            cover/

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: "_build/test/lib/*/test-*.xml"
          
      - name: Compile
        run: mix compile
        env:
          MIX_ENV: test
