name: Docker Build

on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '23 04 * * *'  # Run at 00:00 UTC every day

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        if: ${{ !env.ACT }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: p11ex_test.dockerfile
          push: ${{ !env.ACT }}
#          load: ${{ env.ACT }}
          tags: |
            ghcr.io/${{ github.repository }}/p11ex-test:latest
            ghcr.io/${{ github.repository }}/p11ex-test:${{ github.sha }}
