name: Docker Build

on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '23 04 * * *'  # Run at 00:00 UTC every day

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 120
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            tag: linux-amd64
            runner: ubuntu-latest
          - platform: linux/arm64
            tag: linux-arm64
            runner: [self-hosted, Linux, ARM64]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        if: github.event_name != 'workflow_dispatch'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: p11ex_test.dockerfile
          push: ${{ github.event_name != 'workflow_dispatch' }}
          platforms: ${{ matrix.platform }}
          tags: |
            ghcr.io/${{ github.repository }}/p11ex-test:${{ github.sha }}-${{ matrix.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILDPLATFORM=${{ matrix.platform }}
            TARGETPLATFORM=${{ matrix.platform }}
          provenance: true
          outputs: type=registry,compression=zstd

      - name: Inspect built images
        if: github.event_name != 'workflow_dispatch'
        run: |
          echo "Inspecting SHA-tagged image for ${{ matrix.platform }}:"
          docker manifest inspect ghcr.io/${{ github.repository }}/p11ex-test:${{ github.sha }}-${{ matrix.tag }} | jq .

  manifest:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch'
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull amd64 image
        run: |
          docker pull ghcr.io/${{ github.repository }}/p11ex-test:${{ github.sha }}-linux-amd64

      - name: Pull arm64 image
        run: |
          docker pull ghcr.io/${{ github.repository }}/p11ex-test:${{ github.sha }}-linux-arm64

      - name: Collect image information
        run: |
          docker image inspect ghcr.io/${{ github.repository }}/p11ex-test:${{ github.sha }}-linux-amd64 || true
          docker image inspect ghcr.io/${{ github.repository }}/p11ex-test:${{ github.sha }}-linux-arm64 || true

      - name: Create manifest for the SHA-tagged image
        run: |
          docker manifest create ghcr.io/${{ github.repository }}/p11ex-test:${{ github.sha }} \
            ghcr.io/${{ github.repository }}/p11ex-test:${{ github.sha }}-linux-amd64 \
            ghcr.io/${{ github.repository }}/p11ex-test:${{ github.sha }}-linux-arm64

      - name: Inspect the manifest
        run: |
          docker manifest inspect ghcr.io/${{ github.repository }}/p11ex-test:${{ github.sha }} || true

      - name: Annotate the manifest with the correct OS and architecture
        run: |
          docker manifest annotate ghcr.io/${{ github.repository }}/p11ex-test:${{ github.sha }} \
            ghcr.io/${{ github.repository }}/p11ex-test:${{ github.sha }}-linux-amd64 \
            --os linux --arch amd64

          docker manifest annotate ghcr.io/${{ github.repository }}/p11ex-test:${{ github.sha }} \
            ghcr.io/${{ github.repository }}/p11ex-test:${{ github.sha }}-linux-arm64 \
            --os linux --arch arm64

      - name: Push the manifest
        run: |
          docker manifest push ghcr.io/${{ github.repository }}/p11ex-test:${{ github.sha }}
