name: SoftHSM Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-linux-amd64:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
      contents: read
      packages: read
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Erlang
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.17.0'
          otp-version: '27.3'

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake libtool pkg-config libssl-dev

      - name: Build and install SoftHSM2 from source
        run: |
          cd /tmp
          git clone https://github.com/opendnssec/SoftHSMv2.git
          cd SoftHSMv2
          git checkout 2.6.1  # Latest stable version
          sh autogen.sh
          ./configure --prefix=/usr/local
          make
          sudo make install
          sudo ldconfig
          cd ${{ github.workspace }}

      - name: Setup SoftHSM2
        run: |
          export SOFTHSM2_CONF=$(mktemp)
          export MAKE_TOKEN_DIR=yes
          sh test/softhsm-reset.sh

      - name: Download PKCS#11 headers
        run: |
          cd c_src
          curl -z pkcs11.h -O https://raw.githubusercontent.com/oasis-tcs/pkcs11/master/published/3-01/pkcs11.h
          curl -z pkcs11t.h -O https://raw.githubusercontent.com/oasis-tcs/pkcs11/master/published/3-01/pkcs11t.h
          curl -z pkcs11f.h -O https://raw.githubusercontent.com/oasis-tcs/pkcs11/master/published/3-01/pkcs11f.h
          cd ..

      - name: Install dependencies and run tests
        run: |
          mix local.hex --force
          mix deps.get
          mix compile
          mix test --cover --exclude yubikey

      - name: Upload test results and coverage (linux-amd64)
        uses: actions/upload-artifact@v4
        with:
          name: test-results-linux-amd64.zip
          path: |
            _build/test/lib/*/test-*.xml
            cover/
            cover/excoveralls.json
            doc/

      - name: Publish Test Results (linux-amd64)
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: "_build/test/lib/*/test-*.xml"

  test-linux-arm64:
    runs-on: [self-hosted, Linux, ARM64]
    permissions:
      checks: write
      pull-requests: write
      contents: read
      packages: read
    
    steps:
      - name: Cleanup root-owned files
        if: always()
        run: |
          sudo find ${{ github.workspace }} -user root -exec chown -h ubuntu:ubuntu {} \;
          sudo rm -rf ${{ github.workspace }}/*

      - uses: actions/checkout@v4

      - name: Ensure proper permissions
        run: |
          sudo chown -R ubuntu:ubuntu ${{ github.workspace }}
          sudo chmod -R u+w ${{ github.workspace }}

      - name: Set up Erlang
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.17.0'
          otp-version: '27.3'

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake libtool pkg-config libssl-dev

      - name: Build and install SoftHSM2 from source
        run: |
          cd /tmp
          git clone https://github.com/opendnssec/SoftHSMv2.git
          cd SoftHSMv2
          git checkout 2.6.1  # Latest stable version
          sh autogen.sh
          ./configure --prefix=/usr/local
          make
          sudo make install
          sudo ldconfig
          cd ${{ github.workspace }}

      - name: Setup SoftHSM2
        env:
          PKCS11_MODULE: /usr/local/lib/softhsm/libsofthsm2.so
          SOFTHSM_PREFIX: /usr/local
        run: |
          export SOFTHSM2_CONF=$(mktemp)
          export MAKE_TOKEN_DIR=yes
          
          sh test/softhsm-reset.sh

      - name: Download PKCS#11 headers
        run: |
          cd c_src
          curl -z pkcs11.h -O https://raw.githubusercontent.com/oasis-tcs/pkcs11/master/published/3-01/pkcs11.h
          curl -z pkcs11t.h -O https://raw.githubusercontent.com/oasis-tcs/pkcs11/master/published/3-01/pkcs11t.h
          curl -z pkcs11f.h -O https://raw.githubusercontent.com/oasis-tcs/pkcs11/master/published/3-01/pkcs11f.h
          cd ..

      - name: Install dependencies and run tests
        env:
          PKCS11_MODULE: /usr/local/lib/softhsm/libsofthsm2.so
        run: |
          mix local.hex --force
          mix deps.get
          mix compile
          mix test --cover --exclude yubikey

      - name: Upload test results and coverage (linux-arm64)
        uses: actions/upload-artifact@v4
        with:
          name: test-results-linux-arm64.zip
          path: |
            _build/test/lib/*/test-*.xml
            cover/
            cover/excoveralls.json
            doc/

      - name: Publish Test Results (linux-arm64)
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: "_build/test/lib/*/test-*.xml"

      - name: Cleanup temporary files
        if: always()
        run: |
          sudo rm -rvf ${{ github.workspace }}/_build
          sudo rm -rvf ${{ github.workspace }}/deps
          sudo rm -rvf ${{ github.workspace }}/priv
